# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-01-18 08:43
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('thirukural', '0003_auto_20180117_1232'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='thirukural',
            options={'ordering': ['ChapterName']},
        ),
        migrations.AddField(
            model_name='thirukural',
            name='Kural_number',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='thirukural',
            name='ChapterName',
            field=models.CharField(max_length=30),
        ),
    ]
