# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-01-18 08:52
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('thirukural', '0004_auto_20180118_0843'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='thirukural',
            name='Kural_number',
        ),
    ]
