# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-01-18 08:53
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('thirukural', '0005_remove_thirukural_kural_number'),
    ]

    operations = [
        migrations.AddField(
            model_name='thirukural',
            name='Kural_number',
            field=models.IntegerField(null=True),
        ),
    ]
